# Generated by Django 4.0.4 on 2022-05-31 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('imagen_miniatura', models.ImageField(default='miniaturacapacitaciondefault.jpg', upload_to='miniaturas_capacitaciones')),
                ('imagen_portada', models.ImageField(default='portadacapacitaciondefault.jpg', upload_to='portadas_capacitaciones')),
                ('link_capacitacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('cuerpo', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCursos.capacitacion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField()),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCursos.comentarioforo')),
            ],
        ),
    ]
